/**
 * This class is generated by jOOQ
 */
package com.codebreak.game.persistence.tables.records;


import com.codebreak.game.persistence.tables.Player;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerRecord extends UpdatableRecordImpl<PlayerRecord> {

    private static final long serialVersionUID = -503950130;

    /**
     * Setter for <code>codebreak_game.player.Id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>codebreak_game.player.Name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>codebreak_game.player.AccountId</code>.
     */
    public void setAccountid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>codebreak_game.player.AccountId</code>.
     */
    public Long getAccountid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>codebreak_game.player.Breed</code>.
     */
    public void setBreed(UByte value) {
        set(3, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Breed</code>.
     */
    public UByte getBreed() {
        return (UByte) get(3);
    }

    /**
     * Setter for <code>codebreak_game.player.Color1</code>.
     */
    public void setColor1(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Color1</code>.
     */
    public Integer getColor1() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>codebreak_game.player.Color2</code>.
     */
    public void setColor2(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Color2</code>.
     */
    public Integer getColor2() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>codebreak_game.player.Color3</code>.
     */
    public void setColor3(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Color3</code>.
     */
    public Integer getColor3() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>codebreak_game.player.Skin</code>.
     */
    public void setSkin(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Skin</code>.
     */
    public Integer getSkin() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>codebreak_game.player.SkinSize</code>.
     */
    public void setSkinsize(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>codebreak_game.player.SkinSize</code>.
     */
    public Integer getSkinsize() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>codebreak_game.player.Vitality</code>.
     */
    public void setVitality(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Vitality</code>.
     */
    public Integer getVitality() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>codebreak_game.player.Wisdom</code>.
     */
    public void setWisdom(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Wisdom</code>.
     */
    public Integer getWisdom() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>codebreak_game.player.Strength</code>.
     */
    public void setStrength(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Strength</code>.
     */
    public Integer getStrength() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>codebreak_game.player.Intelligence</code>.
     */
    public void setIntelligence(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Intelligence</code>.
     */
    public Integer getIntelligence() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>codebreak_game.player.Agility</code>.
     */
    public void setAgility(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Agility</code>.
     */
    public Integer getAgility() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>codebreak_game.player.Chance</code>.
     */
    public void setChance(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Chance</code>.
     */
    public Integer getChance() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>codebreak_game.player.Ap</code>.
     */
    public void setAp(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Ap</code>.
     */
    public Integer getAp() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>codebreak_game.player.Mp</code>.
     */
    public void setMp(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Mp</code>.
     */
    public Integer getMp() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>codebreak_game.player.Life</code>.
     */
    public void setLife(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Life</code>.
     */
    public Integer getLife() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>codebreak_game.player.Energy</code>.
     */
    public void setEnergy(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Energy</code>.
     */
    public Integer getEnergy() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>codebreak_game.player.SpellPoint</code>.
     */
    public void setSpellpoint(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>codebreak_game.player.SpellPoint</code>.
     */
    public Integer getSpellpoint() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>codebreak_game.player.CaracPoint</code>.
     */
    public void setCaracpoint(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>codebreak_game.player.CaracPoint</code>.
     */
    public Integer getCaracpoint() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>codebreak_game.player.MapId</code>.
     */
    public void setMapid(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>codebreak_game.player.MapId</code>.
     */
    public Integer getMapid() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>codebreak_game.player.CellId</code>.
     */
    public void setCellid(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>codebreak_game.player.CellId</code>.
     */
    public Integer getCellid() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>codebreak_game.player.Restriction</code>.
     */
    public void setRestriction(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Restriction</code>.
     */
    public Integer getRestriction() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>codebreak_game.player.Experience</code>.
     */
    public void setExperience(Long value) {
        set(24, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Experience</code>.
     */
    public Long getExperience() {
        return (Long) get(24);
    }

    /**
     * Setter for <code>codebreak_game.player.Dead</code>.
     */
    public void setDead(Byte value) {
        set(25, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Dead</code>.
     */
    public Byte getDead() {
        return (Byte) get(25);
    }

    /**
     * Setter for <code>codebreak_game.player.MaxLevel</code>.
     */
    public void setMaxlevel(Integer value) {
        set(26, value);
    }

    /**
     * Getter for <code>codebreak_game.player.MaxLevel</code>.
     */
    public Integer getMaxlevel() {
        return (Integer) get(26);
    }

    /**
     * Setter for <code>codebreak_game.player.DeathCount</code>.
     */
    public void setDeathcount(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>codebreak_game.player.DeathCount</code>.
     */
    public Integer getDeathcount() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>codebreak_game.player.Level</code>.
     */
    public void setLevel(Integer value) {
        set(28, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(28);
    }

    /**
     * Setter for <code>codebreak_game.player.Sex</code>.
     */
    public void setSex(Byte value) {
        set(29, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Sex</code>.
     */
    public Byte getSex() {
        return (Byte) get(29);
    }

    /**
     * Setter for <code>codebreak_game.player.Kamas</code>.
     */
    public void setKamas(Long value) {
        set(30, value);
    }

    /**
     * Getter for <code>codebreak_game.player.Kamas</code>.
     */
    public Long getKamas() {
        return (Long) get(30);
    }

    /**
     * Setter for <code>codebreak_game.player.SavedMapId</code>.
     */
    public void setSavedmapid(Integer value) {
        set(31, value);
    }

    /**
     * Getter for <code>codebreak_game.player.SavedMapId</code>.
     */
    public Integer getSavedmapid() {
        return (Integer) get(31);
    }

    /**
     * Setter for <code>codebreak_game.player.SavedCellId</code>.
     */
    public void setSavedcellid(Integer value) {
        set(32, value);
    }

    /**
     * Getter for <code>codebreak_game.player.SavedCellId</code>.
     */
    public Integer getSavedcellid() {
        return (Integer) get(32);
    }

    /**
     * Setter for <code>codebreak_game.player.MerchantMode</code>.
     */
    public void setMerchantmode(Boolean value) {
        set(33, value);
    }

    /**
     * Getter for <code>codebreak_game.player.MerchantMode</code>.
     */
    public Boolean getMerchantmode() {
        return (Boolean) get(33);
    }

    /**
     * Setter for <code>codebreak_game.player.TitleId</code>.
     */
    public void setTitleid(Integer value) {
        set(34, value);
    }

    /**
     * Getter for <code>codebreak_game.player.TitleId</code>.
     */
    public Integer getTitleid() {
        return (Integer) get(34);
    }

    /**
     * Setter for <code>codebreak_game.player.TitleParams</code>.
     */
    public void setTitleparams(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>codebreak_game.player.TitleParams</code>.
     */
    public String getTitleparams() {
        return (String) get(35);
    }

    /**
     * Setter for <code>codebreak_game.player.EmoteCapacity</code>.
     */
    public void setEmotecapacity(Integer value) {
        set(36, value);
    }

    /**
     * Getter for <code>codebreak_game.player.EmoteCapacity</code>.
     */
    public Integer getEmotecapacity() {
        return (Integer) get(36);
    }

    /**
     * Setter for <code>codebreak_game.player.DeathType</code>.
     */
    public void setDeathtype(Integer value) {
        set(37, value);
    }

    /**
     * Getter for <code>codebreak_game.player.DeathType</code>.
     */
    public Integer getDeathtype() {
        return (Integer) get(37);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerRecord
     */
    public PlayerRecord() {
        super(Player.PLAYER);
    }

    /**
     * Create a detached, initialised PlayerRecord
     */
    public PlayerRecord(Long id, String name, Long accountid, UByte breed, Integer color1, Integer color2, Integer color3, Integer skin, Integer skinsize, Integer vitality, Integer wisdom, Integer strength, Integer intelligence, Integer agility, Integer chance, Integer ap, Integer mp, Integer life, Integer energy, Integer spellpoint, Integer caracpoint, Integer mapid, Integer cellid, Integer restriction, Long experience, Byte dead, Integer maxlevel, Integer deathcount, Integer level, Byte sex, Long kamas, Integer savedmapid, Integer savedcellid, Boolean merchantmode, Integer titleid, String titleparams, Integer emotecapacity, Integer deathtype) {
        super(Player.PLAYER);

        set(0, id);
        set(1, name);
        set(2, accountid);
        set(3, breed);
        set(4, color1);
        set(5, color2);
        set(6, color3);
        set(7, skin);
        set(8, skinsize);
        set(9, vitality);
        set(10, wisdom);
        set(11, strength);
        set(12, intelligence);
        set(13, agility);
        set(14, chance);
        set(15, ap);
        set(16, mp);
        set(17, life);
        set(18, energy);
        set(19, spellpoint);
        set(20, caracpoint);
        set(21, mapid);
        set(22, cellid);
        set(23, restriction);
        set(24, experience);
        set(25, dead);
        set(26, maxlevel);
        set(27, deathcount);
        set(28, level);
        set(29, sex);
        set(30, kamas);
        set(31, savedmapid);
        set(32, savedcellid);
        set(33, merchantmode);
        set(34, titleid);
        set(35, titleparams);
        set(36, emotecapacity);
        set(37, deathtype);
    }
}
