/**
 * This class is generated by jOOQ
 */
package com.codebreak.login.persistence;


import com.codebreak.login.persistence.tables.Account;
import com.codebreak.login.persistence.tables.Gameservice;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodebreakLogin extends SchemaImpl {

    private static final long serialVersionUID = -174296617;

    /**
     * The reference instance of <code>codebreak_login</code>
     */
    public static final CodebreakLogin CODEBREAK_LOGIN = new CodebreakLogin();

    /**
     * The table <code>codebreak_login.account</code>.
     */
    public final Account ACCOUNT = com.codebreak.login.persistence.tables.Account.ACCOUNT;

    /**
     * The table <code>codebreak_login.gameservice</code>.
     */
    public final Gameservice GAMESERVICE = com.codebreak.login.persistence.tables.Gameservice.GAMESERVICE;

    /**
     * No further instances allowed
     */
    private CodebreakLogin() {
        super("codebreak_login", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Gameservice.GAMESERVICE);
    }
}
