/**
 * This class is generated by jOOQ
 */
package com.codebreak.game.persistence;


import com.codebreak.game.persistence.tables.Account;
import com.codebreak.game.persistence.tables.Player;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodebreakGame extends SchemaImpl {

    private static final long serialVersionUID = -196383723;

    /**
     * The reference instance of <code>codebreak_game</code>
     */
    public static final CodebreakGame CODEBREAK_GAME = new CodebreakGame();

    /**
     * The table <code>codebreak_game.account</code>.
     */
    public final Account ACCOUNT = com.codebreak.game.persistence.tables.Account.ACCOUNT;

    /**
     * The table <code>codebreak_game.player</code>.
     */
    public final Player PLAYER = com.codebreak.game.persistence.tables.Player.PLAYER;

    /**
     * No further instances allowed
     */
    private CodebreakGame() {
        super("codebreak_game", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Player.PLAYER);
    }
}
