/**
 * This class is generated by jOOQ
 */
package com.codebreak.game.persistence;


import com.codebreak.game.persistence.tables.Account;
import com.codebreak.game.persistence.tables.Player;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in codebreak_game
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>codebreak_game.account</code>.
     */
    public static final Account ACCOUNT = com.codebreak.game.persistence.tables.Account.ACCOUNT;

    /**
     * The table <code>codebreak_game.player</code>.
     */
    public static final Player PLAYER = com.codebreak.game.persistence.tables.Player.PLAYER;
}
